# Generated by Django 4.2.4 on 2023-08-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='chats',
            name='sender',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
