# Generated by Django 4.2.4 on 2023-08-17 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chats_name_alter_chats_sender'),
    ]

    operations = [
    ]
