# Generated by Django 4.2.4 on 2023-08-17 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_auto_20230817_1726'),
    ]

    operations = [
    ]
